#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OpenNebula Driver for Linstor
Copyright 2018 LINBIT USA LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import print_function

import sys
import subprocess
from one import util, vm
from one.datastore import Datastore
from one.extender import delete_vm_contexts

DST = sys.argv[-3]
VM_ID = int(sys.argv[-2])
DS_ID = sys.argv[-1]


def main():
    util.log_info("Entering tm/context on {h}.".format(h=DST))

    datastore = Datastore(util.show_ds(DS_ID))
    target_vm = vm.Vm(util.show_vm(VM_ID))

    # cleanup old context images no longer needed since v3.x
    if target_vm.has_context:
        del_result = delete_vm_contexts(datastore.linstor_controllers, VM_ID, target_vm.context_id)

        for res in del_result:
            if del_result[res] is not None:
                util.log_info(str(del_result[res]))
    else:
        util.log_info("No CONTEXT section in VM({vm}) XML info".format(vm=VM_ID))

    arguments = sys.argv[1:]
    cmd = ["/var/lib/one/remotes/tm/ssh/context"] + arguments
    process = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    util.log_info("tm/ssh/context finished with {r}.".format(r=process.returncode))
    sys.exit(process.returncode)


if __name__ == "__main__":
    util.run_main(main)
