#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
OpenNebula Driver for Linstor
Copyright 2018 LINBIT USA LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import print_function

import sys
import traceback

from linstor_helper import clone, CloneMode
from linstor import Resource
from one import util, vm
from one.datastore import Datastore

SRC = sys.argv[1]
DST = sys.argv[2]
VM_ID = sys.argv[4]
DS_ID = sys.argv[5]


def main():
    util.log_info("Entering tm cpds with " + str(sys.argv[1:]))

    disk_ID = SRC.split(".")[-1].strip()
    datastore = Datastore(util.show_ds(DS_ID))

    target_vm = vm.Vm(util.show_vm(VM_ID))

    res_name = target_vm.disk_source(disk_ID)
    if target_vm.disk_persistent(disk_ID) != "YES":
        res_name = "{}-vm{}-disk{}".format(res_name, VM_ID, disk_ID)

    res = Resource(res_name, datastore.linstor_controllers)
    success = clone(
        res,
        DST,
        datastore.deployment_nodes,
        datastore.auto_place,
        CloneMode.from_str(datastore.linstor_clone_mode)
    )

    util.log_info("Exiting tm cpds with " + "success." if success else "error.")

    if not success:
        sys.exit(1)


if __name__ == "__main__":
    try:
        main()
    except Exception as err:
        util.error_message(traceback.format_exc())
        print("ERROR: " + str(err))
        raise
