#!/usr/bin/env python3
"""
OpenNebula Driver for Linstor
Copyright 2018 LINBIT USA LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import os
import sys

from one import util
from one.datastore import Datastore
from one.extender import get_device_path, make_resource

SRC = sys.argv[1]
DST = sys.argv[2]
VM_ID = sys.argv[3]
DS_ID = sys.argv[4]


def main():
    util.log_info("Entering tm ln")

    src_path = util.arg_path(SRC).strip()

    dst_host = util.arg_host(DST).strip()
    dst_path = util.arg_path(DST).strip()
    dst_dir = os.path.dirname(dst_path).strip()

    datastore = Datastore(util.show_ds(DS_ID))

    res = make_resource(src_path, datastore.linstor_controllers, datastore.linstor_controller_auth_token)
    res.activate(dst_host)

    util.link_file(dst_host, dst_dir, dst_path, get_device_path(res), res.name)

    util.log_info("Exiting tm ln")


if __name__ == "__main__":
    util.run_main(main)
