#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
OpenNebula Driver for Linstor
Copyright 2019 LINBIT USA LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import print_function

import sys
import os
import traceback

from one import util, consts
from one.datastore import Datastore
from linstor_helper import deploy, get_device_path
from linstor import Resource, Volume, SizeCalc

SIZE = sys.argv[1]
FORMAT = sys.argv[2]
DST = sys.argv[3]
VM_ID = sys.argv[4]
DS_ID = sys.argv[5]


def main():
    util.log_info("Entering tm/mkimage on {h} size {s}.".format(h=DST, s=SIZE))

    disk_id = DST.split(".")[-1].strip()

    dst_host = util.arg_host(DST).strip()
    dst_path = util.arg_path(DST).strip()
    dst_dir = os.path.dirname(dst_path).strip()

    datastore = Datastore(util.show_ds(DS_ID))

    res_name = consts.VOLATILE_PREFIX + "-vm{vm_id}-disk{disk_id}".format(vm_id=VM_ID, disk_id=disk_id)
    resource = Resource(res_name, datastore.linstor_controllers)
    resource.placement.storage_pool = datastore.storage_pool
    resource.volumes[0] = Volume('{s}Mib'.format(s=SIZE))

    deploy(resource, datastore.deployment_nodes, datastore.auto_place)

    resource.activate(dst_host)

    device_path = get_device_path(resource)

    register_command = """cat << EOF
      set -e

      export PATH=/usr/sbin:/sbin:$PATH

      if [ -z "{0}" ] || [ "{0}" == "raw" ]; then exit 0;
      fi

      $SUDO $(mkfs_command "{1}" "{0}" "{2}")

    EOF""".format(
        FORMAT,
        device_path,
        SizeCalc.convert(resource.volumes[0].size, SizeCalc.UNIT_B, SizeCalc.UNIT_MiB)
    )

    rc = util.ssh_exec_and_log(
        " ".join(
            [
                dst_host,
                register_command,
                "Error mkimage {}, on {}".format(device_path, dst_host),
            ]
        )
    )

    if rc != 0:
        sys.exit(rc)

    # link drbd device
    link_command = " ; ".join(
        [
            "set -e",
            "mkdir -p {}".format(dst_dir),
            "ln -fs {} {}".format(device_path, dst_path),
        ]
    )

    rc = util.ssh_exec_and_log(
        " ".join(
            [
                '"{}"'.format(dst_host),
                '"{}"'.format(link_command),
                '"Error: Unable to link {} to {} on {}"'.format(
                    res_name, dst_path, dst_host
                ),
            ]
        )
    )

    if rc != 0:
        sys.exit(rc)

    util.log_info("Leaving tm/mkimage successfully.")


if __name__ == "__main__":
    try:
        main()
    except Exception as err:
        util.error_message(traceback.format_exc())
        print("ERROR: " + str(err))
        raise
