#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OpenNebula Driver for Linstor
Copyright 2018 LINBIT USA LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


import sys

from linstor import Resource
from one import consts, util, vm
from one.datastore import Datastore

SRC = sys.argv[1]
SNAP_ID = sys.argv[2]
VM_ID = int(sys.argv[3])
DS_ID = sys.argv[4]


def main():
    util.log_info("Entering tm/snap_create")

    disk_id = SRC.split(".")[-1].strip()
    snap_id = util.arg_host(SNAP_ID).strip()

    datastore = Datastore(util.show_ds(DS_ID))

    target_vm = vm.Vm(util.show_vm(VM_ID))

    res_name = target_vm.disk_source(disk_id)
    if target_vm.disk_persistent(disk_id) != "YES":
        res_name = "{}-vm{}-disk{}".format(res_name, VM_ID, disk_id)

    res = Resource(name=res_name, uri=datastore.linstor_controllers)

    res.snapshot_create("{}-{}".format(consts.SNAP_PREFIX, snap_id))

    util.log_info("Exiting tm/snap_create")


if __name__ == "__main__":
    util.run_main(main)
