#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OpenNebula Driver for Linstor
Copyright 2018 LINBIT USA LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from __future__ import print_function

import base64
import sys
import traceback

import linstor
from linstor_helper import calculate_space
from one import driver_action, util

DRIVER_ACTION = sys.argv[1]


def main():
    util.log_info("Entering datastore monitor.")

    driver = driver_action.DriverAction(base64.b64decode(DRIVER_ACTION))

    with linstor.MultiLinstor(linstor.MultiLinstor.controller_uri_list(driver.datastore.linstor_controllers)) as lin:
        stor_pool_used, stor_pool_total, stor_pool_free = calculate_space(
            lin,
            driver.datastore.storage_pool,
            driver.datastore.deployment_nodes,
            driver.datastore.auto_place
        )

        print(
            "USED_MB={}\nTOTAL_MB={}\nFREE_MB={}".format(
                stor_pool_used,
                stor_pool_total,
                stor_pool_free,
            )
        )

    util.log_info("Exiting datastore monitor[{u}/{t}/{f}].".format(
        u=stor_pool_used, t=stor_pool_total, f=stor_pool_free)
    )


if __name__ == "__main__":
    try:
        main()
    except Exception as err:
        util.error_message(traceback.format_exc())
        print("ERROR: " + str(err))
        raise
