#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OpenNebula Driver for Linstor
Copyright 2018 LINBIT USA LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


from __future__ import print_function

from one.extender import delete
from one import consts, util, driver_action


def main():
    arg_driver_action, arg_image_id = util.get_datastore_args()

    rscname = "{}-{}".format(consts.IMAGE_PREFIX, arg_image_id)
    util.log_info("Entering datastore rm, deleting resource '{n}'".format(n=rscname))

    driver = driver_action.DriverAction(arg_driver_action)

    delete(rscname, driver.datastore.linstor_controllers)

    util.log_info("Exiting datastore rm.")


if __name__ == "__main__":
    util.run_main(main)
