#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OpenNebula Driver for Linstor
Copyright 2018 LINBIT USA LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


import sys
import traceback
import base64

from linstor import Resource
from one import consts, driver_action, util

DRIVER_ACTION = sys.argv[1]
IMAGE_ID = sys.argv[2]


def main():
    util.log_info("Entering datastore/snap_revert")
    driver = driver_action.DriverAction(base64.b64decode(DRIVER_ACTION))
    snapshot_name = "{}-{}".format(consts.SNAP_PREFIX, driver.image.target_snap)

    res = Resource(name=driver.image.source, uri=driver.datastore.linstor_controllers)
    res.snapshot_rollback(snapshot_name)

    util.log_info("Exiting datastore/snap_revert")


if __name__ == "__main__":
    try:
        main()
    except Exception as err:
        util.error_message(traceback.format_exc())
        print("ERROR: " + str(err))
        raise
