before_script:
  # setup ssh access to clone python-linstor dep
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $CI_SERVER_HOST >> ~/.ssh/known_hosts
  # now install python-linstor into venv
  - pushd /tmp
  - python -m venv venv
  - git clone --recursive git@$CI_SERVER_HOST:linstor/linstor-api-py.git
  - cd linstor-api-py
  - ../venv/bin/python setup.py install
  - ../venv/bin/pip install --trusted-host pypi.python.org xmlrunner
  - popd

test:3.6:
  stage: test
  image: python:3.6
  script:
    - /tmp/venv/bin/python tests.py
  artifacts:
    reports:
      junit: test-reports/TEST-*.xml

test:3.8:
  stage: test
  image: python:3.8
  script:
    - /tmp/venv/bin/python tests.py
  artifacts:
    reports:
      junit: test-reports/TEST-*.xml
